= v1.4.0 → v1.5.0

parent-pom v1.4.0 -> v1.5.0 migrációs leírás, újdonságok, változások leírása

== Újdonságok

=== parent-pom

.Plugin csere:
* org.sonatype.plugins:nexus-staging-maven-plugin 1.6.13 -> org.sonatype.central:central-publishing-maven-plugin 0.8.0

.GitHub release workflow átállás:
* Custom workflow -> `speter555/gh-action-mvn-release-main@v0.32.0`

== Bugfix-ek

=== maven-deploy-plugin konfiguráció

* Jelenleg a maven-deploy-plugin 3.1.1-es verzióját használjuk. A 3.0.0-ás verzió óta a `uniqueVersion` konfigurációs
pareméter teljesen megszűntetésre került, így mi is eltávolítottuk a konfigurációnkból.
(https://maven.apache.org/plugins-archives/maven-deploy-plugin-3.0.0/#major-version-upgrade-to-version-3-0-0)

==== Átállás

* Open Source Maven projektek a https://github.com/i-Cell-Mobilsoft-Open-Source alatt, akik a `parent-oss-pom`-ot használják frissíteniük kell Sonatype bejelentkezési adataikat
és szerver azonosítóikat a GitHub workflow-kban és a settings.xml fájlban a következőképpen:
** server-id: ossrh -> central
** secrets.OSS_SONATYPE_ORG_USER -> secrets.CENTRAL_SONATYPE_ORG_USER
** secrets.OSS_SONATYPE_ORG_PASSWORD -> secrets.CENTRAL_SONATYPE_ORG_PASSWORD
